services:
  api_gateway:
    build: ./apps/http-api-gateway
    ports:
      - "4000:4000"
    volumes:
      - ./apps/http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=4000
  users_microservice:
    build: ./apps/users_microservice
    volumes:
      - ./apps/users-microservice/src:/usr/src/app/src
    command: npm run start:dev
  chats_microservice:
    build: ./apps/users_microservice
    volumes:
      - ./apps/users-microservice/src:/usr/src/app/src
    command: npm run start:dev
